### ISSUE TITLE
Solar value in LUX

### ISSUE THREAD

**Issue by codystoica** [Xorfor/HA-PWS#1]
Hello!
You did a great job with these plugins. From my point of view, they are the most useful of all domoticz plugins, but strangely, they have not been approached by other programmers. I saw that you no longer support for improvement but I wonder if it is possible to import from my PWS the  LUX value form solar sensor. All data is imported correctly from PWS WH2650A but I needed LUX value rather than w/m2
Thanks!

**Comment by Xorfor** [comment]
Just to be sure: you posted this issue in the Home Assistant PWS, but you are talking about the Domoticz plugin?

And an other question: Your PWS is sending the data of the solar sensor in Lux instead of W/m2? Or do you want the received data to be converted to Lux?
In the last case I can add an extra custom device which will show the solar radiation in Lux.

**Comment by codystoica** [comment]
I really posted by mistake, I didn't notice that you have a plugin for HA PWS, I searched for PWS and ... sorry
in my case it's Domoticz.
The PWS sensor transmits the information in three preselected modes fc, lux and w / m2.
Domiticz imports only in w / m2. I need the values ​​in LUX especially when the value in w / m2 is 0.0, I noticed that Domoticz imports only one decimal place.
For example, when Domoticz displays the value 0.0, the station reports 4 lux or 0.02 w / m2. I don't think a converter would help because I don't know the conversion factor for my sensor, it would help me the most for Domoticz to import the value of the solar sensor directly into LUX
![Domoticz](https://user-images.githubusercontent.com/77228515/145721239-1fe9f30b-5ad1-4bb6-86fb-45ec645e7171.jpeg)
![W_m2](https://user-images.githubusercontent.com/77228515/145721250-3e903499-4d3b-4367-b578-e69c41a9363c.jpeg)
![lux](https://user-images.githubusercontent.com/77228515/145721252-03611900-f465-4515-bd8c-7b5dc9b16132.jpeg)

**Comment by Xorfor** [comment]
I just placed a new version on https://github.com/Xorfor/Domoticz-PWS-Plugin.
The plugin will create an extra device (no default), named Solar Radiation, but with Lux as unit.

Can you please test this one? As far as I can see, it should work.

Be aware that W/m2 is the official SI unit for solar radiation.

**Comment by codystoica** [comment]
Hello again!
I installed the update successfully, the new custom device appeared in Domoticz and shows solar radiation in LUX, only at low values ​​what interests me does not calculate. From what I noticed, if the value in w/m2 that PWS transmits is less than 0.1w/m2, the conversion is no longer done. Script does not import values with two decimal.
e.g. 0.09w/m2 * 126.7 = 11 lux but in domoticz I get 0.
Do you think you can solve this problem, I really need the values ​​when they are between 1 and 10 lux

**Comment by Xorfor** [comment]
I found the problem and fixed it. If I have 0.05 W/m2, Domoticz will display 0.1 W/m2 and 6 Lux.

Please pull the latest version and let me know.

**Comment by codystoica** [comment]
It seems to be working as it should.
Thank you very much for your time, you are the best!
