### ISSUE TITLE
Invalid config for [template]: [allowed_methods] is an invalid option for [template]

### ISSUE THREAD

**Issue by angry-elf** [Xorfor/HA-PWS#2]
Hi.

After pasting provided yaml into my config I recieving error after HA startup:

```
Logger: homeassistant.config
Source: config.py:867 
First occurred: 11:33:50 (1 occurrences) 
Last logged: 11:33:50

Invalid config for [template]: [allowed_methods] is an invalid option for [template]. Check: template->allowed_methods. (See ?, line ?).
```

Do I need to allow something somewhere to this for working?

I'm using Homeassistant 2023.1.7

**Comment by angry-elf** [comment]
And the same for ```local_only``` variable

```
2023-05-08 11:43:28.176 ERROR (MainThread) [homeassistant.config] Invalid config for [template]: [local_only] is an invalid option for [template]. Check: template->local_only. (See ?, line ?). 
```

**Comment by angry-elf** [comment]
I disabled both this lines and weatherstations seems working now

**Comment by Xorfor** [comment]
Yes you are right. You have 2 options:

1. Remove those lines. You already did this.
2. Or update to the latest HA version!

I added these lines a couple of days ago, because since the last update of HA, these are required.
