### ISSUE TITLE
Domoticz

### ISSUE THREAD

**Issue by Jeffrey13121** [Xorfor/HA-PWS#4]
How can i use the code with domoticz

**Comment by Xorfor** [comment]
@Jeffrey13121 Originally I created this as a plugin for Domoticz (see https://www.domoticz.com/forum/viewtopic.php?t=29165). But I moved to Home Assistant for a couple of reasons. I have removed my respository, but a couple of persons created a fork. One of them (an older version) can be found at: 

https://github.com/kovariktomas/Domoticz-PWS-Plugin

If your are familiar with Python, you can extend the code.

Hope this will help you.

Regards
