### ISSUE TITLE
WLAN-Wetterstation Profi-WSC mit 7-in-1-Sensor - Configurable

### ISSUE THREAD

**Issue by Pawelecc** [Xorfor/HA-PWS#6]
Can 7-in-1 7003360 EAN 4007922075341 stations also be connected directly to Home Assistant? Only the WSLink application detects it. There are only two weather services (wunderground and weathercloud) and a place for your own, but only there is the option to provide the station URL, ID and key. Is there any way to add my station to Home Assistant?

**Comment by Xorfor** [comment]
Sorry, I can't help you. I have no experience with this station and the WSLink application. I suggest to just try to configure the WSLink application. The clue is that your station needs to post now and then its data to HA.
